### ISSUE TITLE
[menu-button] Popover does not consistently close when clicking between Menu Buttons

### ISSUE THREAD

**Issue by impulse** [reach/reach-ui#566]
### Current Behavior

![reachbug2](https://user-images.githubusercontent.com/8146736/80479338-29819000-894f-11ea-8d3b-6a7d42beede3.gif)

### Expected behavior

Dropdown of the previously clicked menu item should always close.

### Reproducible example

https://codesandbox.io/s/inspiring-goodall-02zhd?file=/src/index.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   @reach/menu-button      |        0.10.1     |
| React            |        react, react-dom     |    16.13.1     |
| Browser          |    Chromium     |    81.0.4044.113     |
| Browser          |    Firefox     |    75.0    |
| Assistive tech   |   -      |     -    |
| Node             |    nodejs     |  v13.12.0       |
| npm/yarn         |     yarn    |  1.22.4       |
| Operating System |   macOS      |   10.15.4      |

**Comment by raunofreiberg** [comment]
I took a quick look at this and it seems like `buttonClickedRef` is causing this problem. Specifically, in this function here:

https://github.com/reach/reach-ui/blob/25840c3d15278e316cc74eaecf096fa01377f361/packages/menu-button/src/index.tsx#L857-L874

The `else` branch is never reached _sometimes_ when clicking between two menus. 

<hr />

There is a comment about using this ref:

https://github.com/reach/reach-ui/blob/25840c3d15278e316cc74eaecf096fa01377f361/packages/menu-button/src/index.tsx#L110-L114

Yet, I don't understand why this would be a problem, if the listener checks for `isExpanded` before doing anything.

cc @chancestrickland

**Comment by raunofreiberg** [comment]
Okay. Digging more into this. I think what happens is that `buttonClickedRef` is set to `true` during `onMouseDown`, but it is never set to `false` when closing the menu since the `else` branch in the global listener does not run. 

I think the correct fix here would be to set `buttonClickedRef` to `false` during `onMouseUp` in `MenuButton`. Although, I'm still not certain tracking this state in a ref is even necessary in the first place.

**Comment by chancestrickland** [comment]
That's a great head start @raunofreiberg, thanks for digging in here! We'll likely use a similar state machine eventually but for now a simple fix will be great. I'll take a look this afternoon.

**Comment by raunofreiberg** [comment]
@chancestrickland shall we do something about this? Folks are starting to patch `@reach/menu-button` to fix this issue. I can open a PR if you'd like 🙂

**Comment by johnwcallahan** [comment]
Hi @chancestrickland and @raunofreiberg, any update on this? The patch we were using no longer works after upgrading from `0.9.1` to `0.11.2`. I spent a little time in the code, but can't quite work out what's going wrong. Thanks in advance!

**Comment by jescowuester** [comment]
I'm having the same issue with the Listbox component (after 0.12). Should I open a new issue for that?

**Comment by sezeregrek** [comment]
I have the same issue @chaance https://codesandbox.io/s/rl90f

**Comment by h0rhay** [comment]
I have similar issue. 1st click outside the nav element does not close it.
I've update to React 17.0.0, and @reach/menu-button 0.15.0
Is this still a bug? Or is it resolved?
Many thanks @chaance 🙏

**Comment by chaance** [comment]
Should be fixed in 0.15.1!

**Comment by happylinks** [comment]
Thanks for this! Much appreciated 😊

**Comment by h0rhay** [comment]
Hey Chance,
Thanks for fixing this one..
Amazing !

Cheers

George

**Comment by iliatcymbal** [comment]
Issue is still reproduced if we use `MenuPopover` instead of `MenuList`. 
https://codesandbox.io/s/friendly-darwin-zf50o?file=/src/index.js

![popoverIssues](https://user-images.githubusercontent.com/6584990/120697949-08c32c80-c4b7-11eb-9ce6-5c749ca2967c.gif)

**Comment by chaance** [comment]
> Issue is still reproduced if we use `MenuPopover` instead of `MenuList`.
> https://codesandbox.io/s/friendly-darwin-zf50o?file=/src/index.js
> 
> ![popoverIssues](https://user-images.githubusercontent.com/6584990/120697949-08c32c80-c4b7-11eb-9ce6-5c749ca2967c.gif)

@iliatcymbal If you use `MenuPopover` you also need to pass `MenuItems` as a child that wraps `MenuItem`s. You can override our styles pretty simply if that's your concern, but you still need to include `MenuItems` for both accessibility and core functionality to remain intact. https://reach.tech/menu-button#menupopover

Issue is resolved for me here: https://codesandbox.io/s/determined-mirzakhani-81r7t?file=/src/index.js

**Comment by iliatcymbal** [comment]
@chaance many thanks!

**Comment by ml242** [comment]
@chaance - this is an old thread, but your description was super helpful to fix the two menus open bug. thanks, it was not obvious to me what was going on.
